apiVersion: v1
kind: Pod
metadata:
  name: spark-tekton-demo-{{ run_id }}
  labels:
    spark-app-id: '{{ run_id }}'
spec:
  metadata:
    name: spark-app
  restartPolicy: Never
  containers:
    - name: spark-app
      image: spark-tekton-demo:latest
      resources:
        limits:
          cpu: '1'
          memory: 2Gi
        requests:
          cpu: '1'
          memory: 1Gi
      env:
        - name: S2I_SPARK_CLUSTER
          value: ephemeral
        - name: S2I_SPARK_RUN_ID
          value: '{{ run_id }}'
        - name: S2I_SPARK_APP
          value: '{{ spark_app }}'
