apiVersion: batch/v1
kind: Job
metadata:
  generateName: spark-app-
spec:
  template:
    metadata:
      name: spark-app
    spec:
      containers:
        - name: spark-app
          image: spark-app:latest
          env:
            - name: S2I_SPARK_CLUSTER
              value: ephemeral
          command:
            - '/opt/spark-app/s2i/bin/run'
      restartPolicy: Never
