apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: spark-app
spec:
  params:
    - name: NAMESPACE
      type: string
    - name: BUILDER_IMAGE
      type: string
      default: quay.io/erikerlandson/spark-app-s2i:latest
  resources:
    - name: git-spark-app
      type: git
  tasks:
    - name: build-spark-app-image
      taskRef:
        kind: Task
        name: s2i-spark-app
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: OUTPUT_IMAGE_URL
          value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/spark-app:latest
        - name: PATH_CONTEXT
          value: examples/spark-pi
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: git-spark-app
    - name: run-spark-app-job
      runAfter:
        - build-spark-app-image
      taskRef:
        kind: Task
        name: openshift-client
      params:
        - name: ARGS
          value:
            - 'create'
            - '-f'
            - 'https://raw.githubusercontent.com/erikerlandson/spark-app-s2i/main/deploy/job-spark-app.yaml'
