apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: spark-app
spec:
  params:
    - name: BUILDER_IMAGE
      type: string
      default: quay.io/erikerlandson/spark-app-s2i:latest
    - name: NAMESPACE
      type: string
      default: 'atos'
    - name: PATH_CONTEXT
      type: string
      default: .
  resources:
    - name: git-spark-app
      type: git
  tasks:
    - name: build-spark-app-image
      taskRef:
        kind: Task
        name: s2i-spark-app
      params:
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
        - name: OUTPUT_IMAGE_URL
          value: image-registry.openshift-image-registry.svc:5000/$(params.NAMESPACE)/spark-app:latest
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: TLSVERIFY
          value: 'false'
      resources:
        inputs:
          - name: source
            resource: git-spark-app
