apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-spark-app
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/erikerlandson/spark-app-s2i.git
