apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: apply-yaml-files
spec:
  inputs:
    params:
      - name: YAML_FILES
        type: array
        description: |
          assumes filenames are of form:
          f1.yaml
          f2.yaml ...
      - name: YAML_DIR
        type: string
        description: subdirectory to find yaml files
        default: .
  workspaces:
    - name: yamldata
      readOnly: true
      mountPath: /yamldata
  steps:
    - name: oc-apply-files
      image: quay.io/openshift/origin-cli:latest
      script: |
        cd /yamldata/$(inputs.params.YAML_DIR)
        for yf in "$@"; do
            echo "applying yaml file $yf"
            oc apply -f $yf
        done
      args:
        - '$(inputs.params.YAML_FILES[*])'
