apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: s2i-spark-app
spec:
  inputs:
    params:
    - description: The location of the s2i builder image.
      name: BUILDER_IMAGE
    - default: .
      description: The location of the path to run s2i from.
      name: PATH_CONTEXT
    - default: 'true'
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      name: TLSVERIFY
    - name: LOGLEVEL
      description: Log level when running the S2I binary
      default: '0'
    - name: OUTPUT_IMAGE_URL
      description: url of created image (expected to be set from parent pipeline)
    resources:
    - name: source
      type: git
  steps:
  - command:
    - /usr/local/bin/s2i
    - --loglevel=$(inputs.params.LOGLEVEL)
    - build
    - $(inputs.params.PATH_CONTEXT)
    - $(inputs.params.BUILDER_IMAGE)
    - --scripts-url
    - image:///opt/pyspark-s2i/bin
    - --destination
    - /opt/pyspark-s2i
    - --as-dockerfile
    - /gen-source/Dockerfile.gen
    image: quay.io/openshift-pipeline/s2i:nightly
    name: generate
    volumeMounts:
    - mountPath: /gen-source
      name: gen-source
    workingDir: /workspace/source
  - command:
    - buildah
    - bud
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - --layers
    - -f
    - /gen-source/Dockerfile.gen
    - -t
    - $(inputs.params.OUTPUT_IMAGE_URL)
    - .
    image: quay.io/buildah/stable
    name: build
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /gen-source
      name: gen-source
    workingDir: /gen-source
  - command:
    - buildah
    - push
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - $(inputs.params.OUTPUT_IMAGE_URL)
    - docker://$(inputs.params.OUTPUT_IMAGE_URL)
    image: quay.io/buildah/stable
    name: push
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
  volumes:
  - emptyDir: {}
    name: varlibcontainers
  - emptyDir: {}
    name: gen-source
