apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: spark-tekton-demo-pod
spec:
  params:
    - name: BUILDER_IMAGE
      type: string
      default: 'quay.io/erikerlandson/spark-tekton-demo-s2i:latest'
  resources:
    - name: spark-tekton-demo
      type: git
  workspaces:
    # this workspace needs to bind to something persistant, like a PVC (not emptyDir)
    - name: render
  tasks:
    - name: spark-tekton-demo-build
      taskRef:
        kind: Task
        name: spark-tekton-demo-s2i
      params:
        - name: OUTPUT_IMAGE_URL
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/spark-tekton-demo:latest
        - name: PATH_CONTEXT
          value: examples/spark-pi
        - name: TLSVERIFY
          value: 'false'
        - name: BUILDER_IMAGE
          value: $(params.BUILDER_IMAGE)
      resources:
        inputs:
          - name: source
            resource: spark-tekton-demo
    - name: spark-tekton-demo-yaml
      taskRef:
        kind: Task
        name: tekton-jinja
      params:
        - name: TEMPLATE_URLS
          value:
            - 'https://raw.githubusercontent.com/erikerlandson/spark-tekton-demo/main/deploy/templates/spark-tekton-demo-pod.yaml'
        - name: TEMPLATE_VARS
          value:
            - run_id
            - $(context.pipelineRun.uid)
        - name: TEKTON_JINJA_IMAGE
          value: 'quay.io/erikerlandson/tekton-jinja:0.1.0'
      workspaces:
        - name: output
          workspace: render
    - name: spark-tekton-demo-pod
      runAfter:
        - spark-tekton-demo-build
        - spark-tekton-demo-yaml
      taskRef:
        kind: Task
        name: apply-yaml-files
      params:
        - name: YAML_FILES
          value:
            - 'job-spark-app.yaml'
        - name: YAML_DIR
          value: rendered
      workspaces:
        - name: yamldata
          workspace: render
